### PR TITLE
Change babylon-provider to template

### PR DESCRIPTION
**Pull request by tylerauerbeck**
This changes `babylon-provider.yml` to a template so that we can parameterize the `ANARCHY_NAMESPACE`. Previously this was hard-coded and wouldn't work if anarchy was deployed to a different namespace.

### CODE REVIEW

**Comment by tylerauerbeck** [comment]
I can get these merge conflicts resolved -- just wanted to see if there are any concerns with going this route first.

**Comment by jkupferer** [comment]
Sounds like a good approach to me. Thanks!

**Comment by jkupferer** [comment]
We will need to coordinate a change to the babylon config repo:
https://github.com/redhat-cop/babylon/blob/master/openshift/config/common/main.yaml#L17

**Comment by jkupferer** [comment]
Replaced by functionality in Helm chart.

**Pull request closed without merging**
